"""Add progress_json to training_execution

Revision ID: 8ec14381ca7c
Revises: 
Create Date: 2025-07-14 02:38:22.418317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8ec14381ca7c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def downgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshot')
    op.drop_table('training_execution')
    op.drop_table('preprocess')
    op.drop_table('model_deployment')
    op.drop_table('preprocess_parents')
    op.drop_table('deployment')
    op.drop_table('execution_snapshots')
    op.drop_table('training')
    op.drop_table('datasource')
    op.drop_table('executed_preprocess')
    # ### end Alembic commands ###


def upgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executed_preprocess',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('preprocess_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('details_json', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['preprocess_id'], ['preprocess.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasource',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('schema_json', sa.VARCHAR(), nullable=True),
    sa.Column('active_snapshot_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['active_snapshot_id'], ['snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('datasource_id', sa.VARCHAR(), nullable=False),
    sa.Column('config_json', sa.VARCHAR(), nullable=False),
    sa.Column('input_schema_json', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('automation_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('automation_schedule', sa.VARCHAR(), nullable=True),
    sa.Column('promotion_metrics', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_snapshots',
    sa.Column('executed_preprocess_id', sa.VARCHAR(), nullable=False),
    sa.Column('snapshot_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['executed_preprocess_id'], ['executed_preprocess.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot.id'], ),
    sa.PrimaryKeyConstraint('executed_preprocess_id', 'snapshot_id')
    )
    op.create_table('deployment',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('training_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['training_id'], ['training.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preprocess_parents',
    sa.Column('preprocess_id', sa.VARCHAR(), nullable=False),
    sa.Column('datasource_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasource.id'], ),
    sa.ForeignKeyConstraint(['preprocess_id'], ['preprocess.id'], ),
    sa.PrimaryKeyConstraint('preprocess_id', 'datasource_id')
    )
    op.create_table('model_deployment',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('deployment_id', sa.VARCHAR(), nullable=False),
    sa.Column('training_execution_id', sa.VARCHAR(), nullable=False),
    sa.Column('promotion_type', sa.VARCHAR(), nullable=False),
    sa.Column('metric', sa.VARCHAR(), nullable=True),
    sa.Column('locked', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ),
    sa.ForeignKeyConstraint(['training_execution_id'], ['training_execution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preprocess',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('config', sa.VARCHAR(), nullable=False),
    sa.Column('datasource_child_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['datasource_child_id'], ['datasource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_execution',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('training_id', sa.VARCHAR(), nullable=False),
    sa.Column('snapshot_id', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.Column('metrics_json', sa.VARCHAR(), nullable=True),
    sa.Column('model_path', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['training.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshot',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('path', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('datasource_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


    # ### end Alembic commands ###
